window.LEGADO_SITE_DATA = {
  brand: {
    name: "LEGADO RUN",
    pillars: ["Saude", "Comunidade", "Proposito", "Legado"],
    instagram: "https://instagram.com/legadorun",
    email: "legadorunn@gmail.com",
    whatsapp: "https://chat.whatsapp.com/IEJSDWF9a0ZLIFcD13W5qf",
    gallery: "https://photos.app.goo.gl/bmxkfRYdnv81bCmJ9",
  },
  event: {
    name: "1a Corrida LEGADO RUN",
    date: "2026-11-01T07:00:00-03:00",
    dateLabel: "01.NOV.2026",
    city: "Belo Horizonte - MG",
    location: "Em frente ao Boulevard Shopping",
    address: "Avenida dos Andradas, 3.345",
    distances: ["3K Caminhada", "6K Corrida", "9K Corrida"],
    registration: "https://site.ticketsports.com.br/Inscricao/Categoria.aspx?__idEvento=87806&lang=pt-BR",
    map: "https://www.google.com/maps/search/?api=1&query=Boulevard%20Shopping%20Avenida%20dos%20Andradas%203345%20Belo%20Horizonte%20MG",
    waze: "https://waze.com/ul?q=Boulevard%20Shopping%20Avenida%20dos%20Andradas%203345%20Belo%20Horizonte%20MG&navigate=yes",
    prices: { simple: "R$ 109,90", complete: "R$ 139,90" },
    schedule: [
      ["07h00", "Inicio do evento"],
      ["07h30", "Abertura do evento"],
      ["08h00", "Aquecimento"],
      ["08h15", "Largada 6 km e 9 km"],
      ["08h55", "Largada 3 km"],
      ["10h00", "Show Gospel"],
      ["11h00", "Premiacao e comunicados"],
      ["12h00", "Encerramento"],
    ],
  },
  app: {
    web: "https://legado-run.vercel.app/",
    android: "https://play.google.com/apps/internaltest/4701310693878336021",
    appStore: "",
  },
  partners: [
    { name: "Viagem Perfeita", image: "/assets/logo-viagem-perfeita-oficial.jpeg", group: "Parceiro" },
    { name: "Master Clean Lavanderia", image: "/assets/logo-master-clean.jpeg", group: "Parceiro" },
    { name: "JET", image: "/assets/logo-jet-clean.jpeg", group: "Parceiro" },
    { name: "Soberana Conservadora", image: "/assets/logo-soberana-conservadora-clean.jpeg", group: "Parceiro" },
  ],
  organization: {
    realization: "LEGADO",
    production: "YOAV EVENTOS",
    legalName: "YOAV SOLUCOES E SERVICOS LTDA",
    cnpj: "60.502.538/0001-26",
  },
};
